### ISSUE TITLE
SPM Support

### ISSUE THREAD

**Issue by florentmorin** [rwbutler/Connectivity#19]
Did you plan to support Swift Package Manager? Thanks.

**Comment by rwbutler** [comment]
There are plans to support SPM - I've merged in a PR from @k3zi although the project doesn't build using the new toolchain currently due to lack of iOS SDK support seemingly. Using the following the project still seems to build against the MacOS SDK:

```
swift build -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios13-simulator" -v
```

Hopefully once this is resolved SPM will be supported.

**Comment by rwbutler** [comment]
Should be fully supported now through Xcode 11.0 beta 👍🏻
