### ISSUE TITLE
connectivityURLs is failing with URL - https://www.apple.com

### ISSUE THREAD

**Issue by RameshAran** [rwbutler/Connectivity#33]
Seems like by setting connectivityURLs is working with full URLS like "https://www.apple.com/library/test/success.html" not with "https://www.apple.com". Ideally, expecting an approach to check the connectivity by using just the host names. Which is supported in Apple Reachability.

**Comment by rwbutler** [comment]
That's correct, when setting the `connectivityURLs` property you need to supply the full URL to the page to be checked. Some time ago, the URLs used by iOS followed a consistent structure whereby the success page was always hosted at `/library/test/success.html` however in iOS 13, the URL used is `https://captive.apple.com/hotspot-detect.html` which does not follow this convention. Therefore, the host name alone is not enough information to infer the location of the success page. I also wouldn't want to restrict developers to having to host success pages at a specific path when hosting their own success pages (which is recommended). 

Reachability essentially has to check a routing table for a given network interface to determine whether a path to the destination is available therefore providing the host name alone is appropriate.  Connectivity has to check the hosted success page to determine whether it contains the correct content which is why the path is required over simply providing a base URL. Hope that helps.
