### ISSUE TITLE
https://captive.apple.com/ is not a reliable connectivity check URL

### ISSUE THREAD

**Issue by AleSpero** [rwbutler/Connectivity#41]
**Is your feature request related to a problem? Please describe.**
Many countries around the world (Brazil, United Arab Emirates, China, and more) are blocking the default https://captive.apple.com/ connectivity URL for some reason, and since the default success threshold is set at 75%, the app would report no internet connection every time in one of those countries.

**Describe the solution you'd like**
There are a couple of possible solutions:

1. Lowering the default connectivity threshold to 50%

2. Adding a different HTTPS URL for checking the internet connection (On this one I think it can be hard to find an URL that's ok for all the countries)

3. Strictly enforcing setting a custom URL for developers.

Thanks for the attention and for your hard work on this library. :)

**Comment by rwbutler** [comment]
Thanks for letting me know about this! I wasn't aware that specific connectivity URL is blocked in certain places. I'd like things to continue to function 'out of the box' so I'll lower the default threshold to 50% since I've already added all the connectivity URLs I'm currently aware of. I've always recommended that users of the library host their own connectivity endpoint and use that instead of the examples provided so I may try to make that more prominent in the documentation.

**Comment by AleSpero** [comment]
Ok! Thank you 😄

**Comment by rwbutler** [comment]
No problem! I've just released 3.3.4 which includes the change 👍🏻
