### ISSUE TITLE
How do I monitor the switch from WiFi A to WiFi B?

### ISSUE THREAD

**Issue by tospery** [rwbutler/Connectivity#61]
How do I monitor the switch from WiFi A to WiFi B?

**Comment by honkmaster** [comment]
You may use NEHotspotNetwork. This package is not suitable for this use case.

**Comment by rwbutler** [comment]
Hi @tospery unfortunately the aim of this project is help developers detect whether Internet connectivity is present rather than searching for specific WiFi networks. As @honkmaster replied above the Network Extension framework may be able to help you with this use case:

https://developer.apple.com/documentation/networkextension
