### ISSUE TITLE
Wrong connectivity status returned when app is backgrounded

### ISSUE THREAD

**Issue by bogartpi** [rwbutler/Connectivity#64]
**Describe the bug**
When app is backgrounded and you switch wifi/cellular on connectivity returns 'connected' status instead of connectedViaWiFi/connectedViaCellular.

**To Reproduce**
1. Go to the app and background it with network connection off
2. Wait at least a minute and then switch connection on.
3. When doing connectivity.checkConnectivity it returns 'connected'

Also connectivity.isConnected returns always True even when there is no wifi/cellular connection.

**Smartphone (please complete the following information):**
 - Device: iPhone11
 - OS: iOS15
![Screen Shot 2021-10-27 at 1 20 32 PM](https://user-images.githubusercontent.com/20196525/139048626-1b0d6edf-63b4-44c6-8df6-518214cff56c.png)
![Screen Shot 2021-10-27 at 1 20 43 PM](https://user-images.githubusercontent.com/20196525/139048633-c0aeab2c-6c11-4567-80b9-20e7849eb2a3.png)

**Comment by rwbutler** [comment]
Hi @bogartpi thanks for reporting an issue. Sorry it's taken me a while to getting around to looking at it. It seems you've flagged two issues here:

1) A status of `.connected` can be returned initially instead of `.connectedViaWiFi` or `.connectedViaCellular`.

> This is certainly possible - occasionally a connectivity check can be carried out at a point in time when Reachability records the network interface status as NotReachable. Although the check executes successfully Reachability has reported an incorrect result therefore a status of `.connected` is recorded. Typically the correct Reachability result will be received moments later and the status will be updated to `.connectedViaWiFi` or `.connectedViaCellular` as appropriate.

There are a few options here:
a) Disable polling and set `checkWhenApplicationDidBecomeActive` to `false`. This means that connectivity checks will only be carried out when the Reachability status changes. This will reduce the accuracy of the framework however as checks will be carried out less frequently so I don't recommend this.
b) Switch from using `.systemConfiguration` framework to using the `.network` framework. This means Connectivity will use `NWPathMonitor` instead of Reachability for detection of network interfaces. This tends to be more accurate.

I don't see this issue as being severe at the moment as the correct result of `.connectedViaWiFi` or `.connectedViaCellular` typically follows a result of `.connected` momentarily after.

2) The `isConnected` property returns true even when the device is disconnected. 

> I've spent some time looking at this issue this morning and I'm currently not available to observe this happening. If you believe that this is still occurring please could you attach some steps to reproduce? 

I'm going to close this issue for now as I don't see 1) as being a major issue (although let me know if you believe the impact to be more severe than I'm stating) and 2) doesn't appear to be reproducible in 5.2.0.

If you believe that either issue still exists in 5.2.0 let me know and I'll look into re-opening.
